FROM node:lts-slim AS build

WORKDIR /code

COPY package.json ./
COPY package-lock.json ./
RUN npm install 

COPY . .
RUN npm run build 

FROM nginx:stable-alpine AS prod 

COPY --from=build /code/dist /usr/share/nginx/html/

COPY default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]