# GET http://localhost:3000

# GET http://localhost:3000/users

# GET http://localhost:3000/lists

POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "cdemaria",
  "password": "1234"
}
